### ISSUE TITLE
Allow multiline

### ISSUE THREAD

**Issue by wachunei** [nebil/alto-en-x#1]
Minsal has a version of a double lined stop sign for "Grasas Saturadas" which can't be reproduced here.

I'd suggest detecting the presence of a space and rendering a two lined svg instead.

PS: I did not find any contribution guide or reference so feel free to close this if you're not accepting feature requests, or ask for a PR 😛

**Comment by nebil** [comment]
I have already implemented that feature, and it is scheduled for the next release.
I'm working on some other minor enhancements, before shipping the version 0.2.0. :package:

By the way, I followed a nearly identical approach. The main difference is that the second `tspan` will be brought into play only if necessary—namely, when the width of the text goes beyond a specific threshold.

Thank you. :grinning:

**Comment by nebil** [comment]
I’ve just released the new version. This issue should be fixed by now. :wink:

**Comment by nebil** [comment]
I've just released the new version. This issue should be fixed by now. :wink:
